# Generated by Django 3.0.14 on 2021-05-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210520_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visites',
            new_name='visits',
        ),
    ]
