# Generated by Django 3.0.14 on 2021-06-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='summery',
        ),
    ]
